In [1]:
import pandas as pd
import ast

In [2]:
credits = pd.read_csv('credit_data.csv')
movies = pd.read_csv('movie_data.csv')

In [3]:
credits.info()

<class 'pandas.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   movie_id  4803 non-null   int64
 1   title     4803 non-null   str
 2   cast      4803 non-null   str
 3   crew      4803 non-null   str
dtypes: int64(1), str(3)
memory usage: 33.8 MB

In [4]:
movies.info()

<class 'pandas.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4803 non-null   int64
 1   genres                4803 non-null   str
 2   homepage              1712 non-null   str
 3   id                    4803 non-null   int64
 4   keywords              4803 non-null   str
 5   original_language     4803 non-null   str
 6   original_title        4803 non-null   str
 7   overview              4800 non-null   str
 8   popularity            4803 non-null   float64
 9   production_companies  4803 non-null   str
 10  production_countries  4803 non-null   str
 11  release_date          4802 non-null   str
 12  revenue               4803 non-null   int64
 13  runtime               4801 non-null   float64
 14  spoken_languages      4803 non-null   str
 15  status                4803 non-null   str
 16  tagline               3959 non-null   str
 17  title                 4803 non-null   str
 18  vote_average          4803 non-null   float64
 19  vote_count            4803 non-null   int64
dtypes: float64(3), int64(4), str(13)
memory usage: 5.4 MB

In [5]:
movies = movies[['id','genres','keywords','title','tagline','overview','production_companies']]
credits = credits[['movie_id','cast','crew']]

In [6]:
movies.info()
credits.info()

<class 'pandas.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 7 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    4803 non-null   int64
 1   genres                4803 non-null   str
 2   keywords              4803 non-null   str
 3   title                 4803 non-null   str
 4   tagline               3959 non-null   str
 5   overview              4800 non-null   str
 6   production_companies  4803 non-null   str
dtypes: int64(1), str(6)
memory usage: 4.1 MB
<class 'pandas.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   movie_id  4803 non-null   int64
 1   cast      4803 non-null   str
 2   crew      4803 non-null   str
dtypes: int64(1), str(2)
memory usage: 33.7 MB

In [7]:
# join both dataframes using merge
table = pd.merge(movies, credits, left_on = 'id', right_on = 'movie_id', how = 'inner')

In [8]:
table.drop(columns = ['movie_id'], inplace = True)

In [9]:
table.info()

<class 'pandas.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    4803 non-null   int64
 1   genres                4803 non-null   str
 2   keywords              4803 non-null   str
 3   title                 4803 non-null   str
 4   tagline               3959 non-null   str
 5   overview              4800 non-null   str
 6   production_companies  4803 non-null   str
 7   cast                  4803 non-null   str
 8   crew                  4803 non-null   str
dtypes: int64(1), str(8)
memory usage: 37.7 MB

In [10]:
table

,id,genres,keywords,title,tagline,overview,production_companies,cast,crew
0,19995,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",Avatar,Enter the World of Pandora.,"In the 22nd century, a paraplegic Marine is di...","[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",Pirates of the Caribbean: At World's End,"At the end of the world, the adventure begins.","Captain Barbossa, long believed to be dead, ha...","[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",Spectre,A Plan No One Escapes,A cryptic message from Bond’s past sends him o...,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",The Dark Knight Rises,The Legend Ends,Following the death of District Attorney Harve...,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",John Carter,"Lost in our world, found in another.","John Carter is a war-weary, former military ca...","[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
...,...,...,...,...,...,...,...,...,...
4798,9367,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 5616, ""name"": ""united states\u2013mexi...",El Mariachi,"He didn't come looking for trouble, but troubl...",El Mariachi just wants to play his guitar and ...,"[{""name"": ""Columbia Pictures"", ""id"": 5}]","[{""cast_id"": 1, ""character"": ""El Mariachi"", ""c...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de..."
4799,72766,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",[],Newlyweds,A newlywed couple's honeymoon is upended by th...,A newlywed couple's honeymoon is upended by th...,[],"[{""cast_id"": 1, ""character"": ""Buzzy"", ""credit_...","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de..."
4800,231617,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...","[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...","Signed, Sealed, Delivered",NaN,"""Signed, Sealed, Delivered"" introduces a dedic...","[{""name"": ""Front Street Pictures"", ""id"": 3958}...","[{""cast_id"": 8, ""character"": ""Oliver O\u2019To...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de..."
4801,126186,[],[],Shanghai Calling,A New Yorker in Shanghai,When ambitious New York attorney Sam is sent t...,[],"[{""cast_id"": 3, ""character"": ""Sam"", ""credit_id...","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de..."
4802,25975,"[{""id"": 99, ""name"": ""Documentary""}]","[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...",My Date with Drew,NaN,Ever since the second grade when he first saw ...,"[{""name"": ""rusty bear entertainment"", ""id"": 87...","[{""cast_id"": 3, ""character"": ""Herself"", ""credi...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de..."

In [11]:
data = table.loc[2,'crew']
data

'[{"credit_id": "54805967c3a36829b5002c41", "department": "Sound", "gender": 2, "id": 153, "job": "Original Music Composer", "name": "Thomas Newman"}, {"credit_id": "52fe4d22c3a368484e1d8d77", "department": "Directing", "gender": 2, "id": 39, "job": "Director", "name": "Sam Mendes"}, {"credit_id": "5677cd99925141691a005333", "department": "Art", "gender": 1, "id": 8384, "job": "Set Decoration", "name": "Anna Pinnock"}, {"credit_id": "52fe4d22c3a368484e1d8d8d", "department": "Writing", "gender": 2, "id": 932, "job": "Screenplay", "name": "John Logan"}, {"credit_id": "562fc9bb92514129fe0006b4", "department": "Writing", "gender": 2, "id": 932, "job": "Story", "name": "John Logan"}, {"credit_id": "5654d41c92514145c3000373", "department": "Art", "gender": 2, "id": 4248, "job": "Production Design", "name": "Dennis Gassner"}, {"credit_id": "52fe4d22c3a368484e1d8d71", "department": "Writing", "gender": 2, "id": 9856, "job": "Characters", "name": "Ian Fleming"}, {"credit_id": "54805989c3a36829ae0022d8", "department": "Editing", "gender": 0, "id": 3904, "job": "Editor", "name": "Lee Smith"}, {"credit_id": "5677df82c3a3681683008748", "department": "Sound", "gender": 2, "id": 7538, "job": "Music Editor", "name": "Bill Bernstein"}, {"credit_id": "5720e370c3a368117e00045b", "department": "Production", "gender": 2, "id": 8784, "job": "Co-Producer", "name": "Daniel Craig"}, {"credit_id": "5522fdd09251416d4a0024b6", "department": "Costume & Make-Up", "gender": 1, "id": 11227, "job": "Costume Design", "name": "Jany Temime"}, {"credit_id": "5677cc9ac3a368167c0089b5", "department": "Production", "gender": 1, "id": 10496, "job": "Casting", "name": "Debbie McWilliams"}, {"credit_id": "52fe4d22c3a368484e1d8d7d", "department": "Production", "gender": 1, "id": 10666, "job": "Producer", "name": "Barbara Broccoli"}, {"credit_id": "5720e3afc3a368117e00046a", "department": "Production", "gender": 0, "id": 11268, "job": "Line Producer", "name": "Roberto Malerba"}, {"credit_id": "5677df58c3a368167c008c82", "department": "Sound", "gender": 0, "id": 40827, "job": "Music Editor", "name": "Peter Clarke"}, {"credit_id": "5677dd1ec3a36816890085d3", "department": "Sound", "gender": 0, "id": 14764, "job": "Sound Designer", "name": "Christopher Assells"}, {"credit_id": "566046b9c3a36875f400323a", "department": "Sound", "gender": 0, "id": 14765, "job": "Supervising Sound Editor", "name": "Per Hallberg"}, {"credit_id": "5677ccab925141691a00530f", "department": "Production", "gender": 0, "id": 36108, "job": "Casting", "name": "Nicole Schmied"}, {"credit_id": "5677cfe4c3a36816850087d2", "department": "Production", "gender": 0, "id": 36108, "job": "Casting Associate", "name": "Nicole Schmied"}, {"credit_id": "562fc984c3a3681b5400e16f", "department": "Writing", "gender": 2, "id": 10783, "job": "Screenplay", "name": "Robert Wade"}, {"credit_id": "562fc9cec3a3681b4b00d168", "department": "Writing", "gender": 2, "id": 10783, "job": "Story", "name": "Robert Wade"}, {"credit_id": "562fc976c3a3681b5c00dd64", "department": "Writing", "gender": 0, "id": 10782, "job": "Screenplay", "name": "Neal Purvis"}, {"credit_id": "562fc9d79251414ad800c103", "department": "Writing", "gender": 0, "id": 10782, "job": "Story", "name": "Neal Purvis"}, {"credit_id": "5720e61d9251414235000477", "department": "Production", "gender": 2, "id": 10876, "job": "Executive Producer", "name": "Callum McDougall"}, {"credit_id": "562fc9a89251414ad800c0fe", "department": "Writing", "gender": 2, "id": 21339, "job": "Screenplay", "name": "Jez Butterworth"}, {"credit_id": "570bd7f2c3a36802a9000412", "department": "Art", "gender": 0, "id": 23425, "job": "Supervising Art Director", "name": "Chris Lowe"}, {"credit_id": "5677e45ac3a368168b0084fd", "department": "Art", "gender": 0, "id": 23491, "job": "Assistant Art Director", "name": "Roxana Alexandru "}, {"credit_id": "5677e29c925141691a00561c", "department": "Crew", "gender": 0, "id": 23774, "job": "Makeup Effects", "name": "Jo Grover"}, {"credit_id": "5677cf8492514179d20088ae", "department": "Production", "gender": 2, "id": 10907, "job": "Casting", "name": "St\\u00e9phane Foenkinos"}, {"credit_id": "5677d7b192514179d20089c6", "department": "Camera", "gender": 2, "id": 61851, "job": "Camera Operator", "name": "Lorenzo Senatore"}, {"credit_id": "5720e6f7925141423000046b", "department": "Production", "gender": 0, "id": 64000, "job": "Line Producer", "name": "Wolfgang Ramml"}, {"credit_id": "5677dfabc3a368168000899f", "department": "Sound", "gender": 2, "id": 66941, "job": "Orchestrator", "name": "J.A.C. Redford"}, {"credit_id": "5720e72e92514142320007fc", "department": "Production", "gender": 0, "id": 81517, "job": "Associate Producer", "name": "Gregg Wilson"}, {"credit_id": "52fe4d22c3a368484e1d8d83", "department": "Production", "gender": 2, "id": 69678, "job": "Producer", "name": "Michael G. Wilson"}, {"credit_id": "5720e325c3a368118100043e", "department": "Production", "gender": 0, "id": 77511, "job": "Line Producer", "name": "Zakaria Alaoui"}, {"credit_id": "548059799251416e7e00265c", "department": "Camera", "gender": 0, "id": 74401, "job": "Director of Photography", "name": "Hoyte van Hoytema"}, {"credit_id": "5677cef792514179db00904d", "department": "Crew", "gender": 0, "id": 239885, "job": "Special Effects Coordinator", "name": "Franco Ragusa"}, {"credit_id": "5677d7e992514179e7008654", "department": "Camera", "gender": 0, "id": 937946, "job": "Camera Operator", "name": "Peter Field"}, {"credit_id": "5677cd21c3a3681680008700", "department": "Art", "gender": 2, "id": 979698, "job": "Art Direction", "name": "Neal Callow"}, {"credit_id": "5677cd5a92514179e30086fb", "department": "Art", "gender": 2, "id": 986687, "job": "Art Direction", "name": "Mark Harris"}, {"credit_id": "5678090392514179e1009958", "department": "Crew", "gender": 0, "id": 1024842, "job": "Visual Effects Editor", "name": "Billy A. Campbell"}, {"credit_id": "5720e6749251414240000470", "department": "Production", "gender": 0, "id": 1026247, "job": "Co-Producer", "name": "Stacy Perskie"}, {"credit_id": "56780a2292514179dd008d18", "department": "Visual Effects", "gender": 0, "id": 1029804, "job": "Visual Effects Producer", "name": "Laura Schultz"}, {"credit_id": "5677e174925141691a0055f1", "department": "Costume & Make-Up", "gender": 0, "id": 1087452, "job": "Key Hair Stylist", "name": "Mari Paz Robles"}, {"credit_id": "5677e0cf9251417845001631", "department": "Costume & Make-Up", "gender": 0, "id": 1099281, "job": "Hairstylist", "name": "Gerardo Perez Arreola"}, {"credit_id": "5677d73b92514179dd008471", "department": "Camera", "gender": 0, "id": 1118711, "job": "Camera Operator", "name": "Kenji Katori"}, {"credit_id": "5677cd3a92514179d2008852", "department": "Art", "gender": 0, "id": 1296445, "job": "Art Direction", "name": "Ben Collins"}, {"credit_id": "5677cfc3c3a3681680008755", "department": "Production", "gender": 0, "id": 1305251, "job": "Casting Associate", "name": "Tusse Lande"}, {"credit_id": "5677e24f92514179e70087da", "department": "Costume & Make-Up", "gender": 0, "id": 1315700, "job": "Makeup Artist", "name": "Donald Mowat"}, {"credit_id": "5677d622c3a368167c008b25", "department": "Costume & Make-Up", "gender": 0, "id": 1319160, "job": "Costume Supervisor", "name": "Ken Crouch"}, {"credit_id": "5677cd0ec3a368168e008f75", "department": "Art", "gender": 0, "id": 1335539, "job": "Art Direction", "name": "Andrew Bennett"}, {"credit_id": "56780833925141691a005c2f", "department": "Visual Effects", "gender": 0, "id": 1338241, "job": "Visual Effects Coordinator", "name": "Sean McGrath"}, {"credit_id": "5677dcc7c3a36816830086cc", "department": "Sound", "gender": 0, "id": 1338372, "job": "Foley", "name": "Dan O\'Connell"}, {"credit_id": "56780ac692514179dd008d31", "department": "Visual Effects", "gender": 0, "id": 1341741, "job": "Visual Effects Supervisor", "name": "Mark Curtis"}, {"credit_id": "5677dd9fc3a368168b0083f0", "department": "Sound", "gender": 2, "id": 1341858, "job": "Sound Re-Recording Mixer", "name": "Gregg Rudloff"}, {"credit_id": "566047029251412204002337", "department": "Directing", "gender": 0, "id": 1342669, "job": "Script Supervisor", "name": "Jayne-Ann Tenggren"}, {"credit_id": "5720e713925141423000046d", "department": "Production", "gender": 0, "id": 1342669, "job": "Associate Producer", "name": "Jayne-Ann Tenggren"}, {"credit_id": "5677dd8792514179db009235", "department": "Sound", "gender": 0, "id": 1345595, "job": "Sound Re-Recording Mixer", "name": "Scott Millan"}, {"credit_id": "5677def192514179e700875b", "department": "Directing", "gender": 0, "id": 1358025, "job": "Script Supervisor", "name": "Nicoletta Mani"}, {"credit_id": "5677dcb0925141691a00552a", "department": "Sound", "gender": 0, "id": 1367493, "job": "Foley", "name": "John T. Cucci"}, {"credit_id": "5677d7ff92514179e300884b", "department": "Camera", "gender": 0, "id": 1377503, "job": "Camera Operator", "name": "Sebastian Meuschel"}, {"credit_id": "5677d94192514179d20089ff", "department": "Camera", "gender": 2, "id": 1388897, "job": "Steadicam Operator", "name": "Julian Morson"}, {"credit_id": "5677dce5c3a36816830086d3", "department": "Sound", "gender": 0, "id": 1389614, "job": "Foley", "name": "Peter Michael Sullivan"}, {"credit_id": "56780a5a92514179e300908d", "department": "Visual Effects", "gender": 0, "id": 1391691, "job": "Visual Effects Producer", "name": "Ken Dailey"}, {"credit_id": "5677dd38c3a368167c008c21", "department": "Sound", "gender": 0, "id": 1392083, "job": "Sound Designer", "name": "Ann Scibelli"}, {"credit_id": "5677d7cd92514179db009178", "department": "Camera", "gender": 0, "id": 1392246, "job": "Camera Operator", "name": "Clive Jackson"}, {"credit_id": "5677de6192514179dd008566", "department": "Directing", "gender": 0, "id": 1392661, "job": "Script Supervisor", "name": "Susie Jones"}, {"credit_id": "5677d98fc3a3681685008904", "department": "Camera", "gender": 2, "id": 1392718, "job": "Still Photographer", "name": "Jasin Boland"}, {"credit_id": "5677cdd8c3a368168b0081e1", "department": "Art", "gender": 0, "id": 1394117, "job": "Art Department Coordinator", "name": "Jennifer Lewicki"}, {"credit_id": "5677e58cc3a3681685008adb", "department": "Art", "gender": 0, "id": 1398089, "job": "Greensman", "name": "Ian Whiteford"}, {"credit_id": "56780a7592514179db0099c4", "department": "Visual Effects", "gender": 0, "id": 1398100, "job": "Visual Effects Producer", "name": "Kilou Picard"}, {"credit_id": "5677d8ba92514179d20089f0", "department": "Camera", "gender": 0, "id": 1399071, "job": "Helicopter Camera", "name": "Hans Bjerno"}, {"credit_id": "5677dd02c3a368167a0091a2", "department": "Editing", "gender": 2, "id": 1399862, "job": "Dialogue Editor", "name": "Daniel Saxlid"}, {"credit_id": "5677e2e1c3a368167c008d1a", "department": "Costume & Make-Up", "gender": 0, "id": 1401126, "job": "Wigmaker", "name": "Alex Rouse"}, {"credit_id": "5678096bc3a368167c0093d2", "department": "Crew", "gender": 0, "id": 1401147, "job": "Visual Effects Editor", "name": "Anik Seguin"}, {"credit_id": "5677dc90c3a368167a009190", "department": "Sound", "gender": 0, "id": 1401631, "job": "ADR & Dubbing", "name": "Michelle Pazer"}, {"credit_id": "5677d75ac3a368167a0090e9", "department": "Camera", "gender": 2, "id": 1403411, "job": "Camera Operator", "name": "Lucas Bielan"}, {"credit_id": "566046d7c3a36875e900359d", "department": "Sound", "gender": 0, "id": 1404212, "job": "Supervising Sound Editor", "name": "Karen Baker Landers"}, {"credit_id": "5677dd519251417845001588", "department": "Sound", "gender": 0, "id": 1404217, "job": "Sound Designer", "name": "Peter Staubli"}, {"credit_id": "5677d8d192514179e1009100", "department": "Camera", "gender": 0, "id": 1404244, "job": "Helicopter Camera", "name": "John Marzano"}, {"credit_id": "5677d927c3a36816850088f2", "department": "Camera", "gender": 0, "id": 1405241, "job": "Helicopter Camera", "name": "Adam Dale"}, {"credit_id": "5677dff292514179e100921a", "department": "Editing", "gender": 0, "id": 1408363, "job": "First Assistant Editor", "name": "Emma McCleave"}, {"credit_id": "5677e191925141784500164f", "department": "Costume & Make-Up", "gender": 0, "id": 1409821, "job": "Makeup Designer", "name": "Naomi Donne"}, {"credit_id": "5677e2b5c3a368168e0092aa", "department": "Crew", "gender": 0, "id": 1411323, "job": "Makeup Effects", "name": "Susan Howard"}, {"credit_id": "5677d869c3a36816850088e3", "department": "Lighting", "gender": 0, "id": 1414096, "job": "Gaffer", "name": "David Smith"}, {"credit_id": "56780712c3a368168b008ace", "department": "Crew", "gender": 0, "id": 1415157, "job": "CG Supervisor", "name": "Joel Green"}, {"credit_id": "567806ba92514179e10098ee", "department": "Crew", "gender": 0, "id": 1425484, "job": "CG Supervisor", "name": "Laurent Hugueniot"}, {"credit_id": "56780a92c3a36816850090af", "department": "Visual Effects", "gender": 0, "id": 1425488, "job": "Visual Effects Producer", "name": "Tim Keene"}, {"credit_id": "5677e087c3a368167a00922b", "department": "Costume & Make-Up", "gender": 0, "id": 1425971, "job": "Hair Designer", "name": "Zoe Tahir"}, {"credit_id": "567808eb92514179e300904a", "department": "Crew", "gender": 0, "id": 1428902, "job": "Visual Effects Editor", "name": "Conor Byrne"}, {"credit_id": "5677e22d925141691a00560d", "department": "Costume & Make-Up", "gender": 0, "id": 1439128, "job": "Makeup Artist", "name": "Charlotte Hayward"}, {"credit_id": "5677cf3fc3a36816850087c1", "department": "Visual Effects", "gender": 0, "id": 1442137, "job": "Animation Supervisor", "name": "Catherine Mullan"}, {"credit_id": "56780988c3a3681683008e99", "department": "Crew", "gender": 0, "id": 1447617, "job": "Visual Effects Editor", "name": "Crystal Hadcroft"}, {"credit_id": "5677e0ec925141691a0055d6", "department": "Costume & Make-Up", "gender": 0, "id": 1458416, "job": "Hairstylist", "name": "Francesca Crowder"}, {"credit_id": "5677cf2892514179dd008356", "department": "Visual Effects", "gender": 0, "id": 1459878, "job": "Animation Director", "name": "Marlene Chazot"}, {"credit_id": "5678091d92514179db009985", "department": "Crew", "gender": 0, "id": 1459899, "job": "Visual Effects Editor", "name": "Struan Farquhar"}, {"credit_id": "56780731c3a3681680009013", "department": "Crew", "gender": 0, "id": 1459925, "job": "CG Supervisor", "name": "Daniel Pastore"}, {"credit_id": "5677d969c3a368168b00834a", "department": "Camera", "gender": 0, "id": 1470167, "job": "Still Photographer", "name": "Jonathan Olley"}, {"credit_id": "5677e48dc3a368167a0092c8", "department": "Art", "gender": 0, "id": 1472773, "job": "Assistant Art Director", "name": "Sami Gaidi"}, {"credit_id": "5751eed59251416b60000637", "department": "Production", "gender": 2, "id": 1477203, "job": "Co-Producer", "name": "Luca Marco Paracels"}, {"credit_id": "5677e157c3a36816800089ee", "department": "Costume & Make-Up", "gender": 0, "id": 1480629, "job": "Key Hair Stylist", "name": "Luca Vannella"}, {"credit_id": "56780b0e925141691a005c8f", "department": "Visual Effects", "gender": 0, "id": 1483141, "job": "Visual Effects Supervisor", "name": "Stuart Bullen"}, {"credit_id": "582f29fa925141022e003a74", "department": "Sound", "gender": 0, "id": 1494824, "job": "Sound Effects Editor", "name": "Russell Edwards"}, {"credit_id": "5677d63dc3a368167a0090b4", "department": "Costume & Make-Up", "gender": 0, "id": 1510431, "job": "Costume Supervisor", "name": "Stefano De Nardis"}, {"credit_id": "5677d79992514179d20089c2", "department": "Camera", "gender": 0, "id": 1512767, "job": "Camera Operator", "name": "Luis David Sansans"}, {"credit_id": "5677d609c3a368168000881a", "department": "Costume & Make-Up", "gender": 0, "id": 1545912, "job": "Costume Supervisor", "name": "Abderrahim Benkhayi"}, {"credit_id": "5677d66cc3a368167a0090be", "department": "Costume & Make-Up", "gender": 0, "id": 1545913, "job": "Set Costumer", "name": "Rachid Aadassi"}, {"credit_id": "5677da26c3a368167a009139", "department": "Camera", "gender": 0, "id": 1545995, "job": "Additional Camera", "name": "Carlos De Carvalho"}, {"credit_id": "5677d5bec3a368167c008b13", "department": "Costume & Make-Up", "gender": 0, "id": 1546747, "job": "Assistant Costume Designer", "name": "Vivienne Jones"}, {"credit_id": "5677dfcac3a368168300875b", "department": "Editing", "gender": 0, "id": 1548406, "job": "Digital Intermediate", "name": "Kim Honeyman"}, {"credit_id": "5677e105c3a368168b00846d", "department": "Costume & Make-Up", "gender": 0, "id": 1550637, "job": "Hairstylist", "name": "Kathryn Fa"}, {"credit_id": "5677ce0c9251417845001384", "department": "Crew", "gender": 0, "id": 1551770, "job": "Carpenter", "name": "Paul Duff"}, {"credit_id": "5677ce5192514179e300871b", "department": "Crew", "gender": 0, "id": 1551771, "job": "Property Master", "name": "Ben Wilkinson"}, {"credit_id": "5677cec292514179dd00834d", "department": "Crew", "gender": 0, "id": 1551772, "job": "Special Effects Coordinator", "name": "Lynne Corbould"}, {"credit_id": "5677cf57c3a368168e008fcc", "department": "Production", "gender": 0, "id": 1551773, "job": "Casting", "name": "Amal El-Farfachi"}, {"credit_id": "5677cf99c3a368168b00821d", "department": "Production", "gender": 0, "id": 1551774, "job": "Casting Associate", "name": "Celebrity Booker"}, {"credit_id": "5677cfadc3a368167c008a30", "department": "Production", "gender": 0, "id": 1551775, "job": "Casting Associate", "name": "Lucy Hellier"}, {"credit_id": "5677d5a392514179db00911d", "department": "Costume & Make-Up", "gender": 0, "id": 1551777, "job": "Assistant Costume Designer", "name": "Richard Davies"}, {"credit_id": "5677dd6bc3a368168b0083e2", "department": "Sound", "gender": 0, "id": 1551789, "job": "Sound Effects Editor", "name": "Ando Johnson"}, {"credit_id": "5677de2dc3a3681683008713", "department": "Crew", "gender": 0, "id": 1551791, "job": "Armorer", "name": "Greg Corke"}, {"credit_id": "5677de8a92514179e10091d9", "department": "Production", "gender": 0, "id": 1551796, "job": "Researcher", "name": "Amin Rharda"}, {"credit_id": "5677dea9c3a368168e00921c", "department": "Crew", "gender": 0, "id": 1551797, "job": "Armorer", "name": "Joss Skottowe"}, {"credit_id": "5677e11c92514179dd0085e3", "department": "Costume & Make-Up", "gender": 0, "id": 1551798, "job": "Hairstylist", "name": "Joseph Koniak"}, {"credit_id": "5677e1b19251417845001657", "department": "Costume & Make-Up", "gender": 0, "id": 1551800, "job": "Makeup Artist", "name": "Thal\\u00eda Echeveste"}, {"credit_id": "5677e1c7c3a368167c008cd8", "department": "Costume & Make-Up", "gender": 0, "id": 1551801, "job": "Makeup Artist", "name": "Charlie Hounslow"}, {"credit_id": "5677e1e592514179d2008b7b", "department": "Costume & Make-Up", "gender": 0, "id": 1551802, "job": "Makeup Artist", "name": "Lucy Friend"}, {"credit_id": "5677e1fa92514179e1009265", "department": "Costume & Make-Up", "gender": 0, "id": 1551803, "job": "Makeup Artist", "name": "Yelska Labrada"}, {"credit_id": "5677e20fc3a36816830087d9", "department": "Costume & Make-Up", "gender": 0, "id": 1551804, "job": "Makeup Artist", "name": "Ana Gabriela Quinonez"}, {"credit_id": "5677e32d9251417845001683", "department": "Production", "gender": 0, "id": 1551807, "job": "Researcher", "name": "Gina De Ferrer"}, {"credit_id": "5677e47592514179e10092dd", "department": "Art", "gender": 0, "id": 1551809, "job": "Assistant Art Director", "name": "Lydia Fry"}, {"credit_id": "5677e4a492514179db009373", "department": "Art", "gender": 0, "id": 1551810, "job": "Assistant Art Director", "name": "Liam Georgensen"}, {"credit_id": "5677e4bb92514179dd00868a", "department": "Art", "gender": 0, "id": 1551811, "job": "Assistant Art Director", "name": "Hugh McClelland"}, {"credit_id": "5677e53092514179db00938e", "department": "Crew", "gender": 0, "id": 1551812, "job": "Carpenter", "name": "John Allen"}, {"credit_id": "5677e547c3a368167a0092ef", "department": "Crew", "gender": 0, "id": 1551813, "job": "Carpenter", "name": "Eddie Murphy"}, {"credit_id": "567806e092514179dd008c84", "department": "Crew", "gender": 0, "id": 155

In [12]:
def fetch_data(data):
    a = ast.literal_eval(data)
    data_store = []
    for item in a:
        data_store.append(item['name'])
    comma_data = ','.join(data_store)
    return comma_data

In [13]:
table['genres'] = table['genres'].apply(fetch_data)
table['keywords'] = table['keywords'].apply(fetch_data)
table['production_companies'] = table['production_companies'].apply(fetch_data)
table['cast'] = table['cast'].apply(fetch_data)
table['crew'] = table['crew'].apply(fetch_data)

In [14]:
table['genres'] = table['genres'].str.replace(' ','_')
table['keywords'] = table['keywords'].str.replace(' ','_')
table['production_companies'] = table['production_companies'].str.replace(' ','_')
table['cast'] = table['cast'].str.replace(' ','_')
table['crew'] = table['crew'].str.replace(' ','_')

In [15]:
table

,id,genres,keywords,title,tagline,overview,production_companies,cast,crew
0,19995,"Action,Adventure,Fantasy,Science_Fiction","culture_clash,future,space_war,space_colony,so...",Avatar,Enter the World of Pandora.,"In the 22nd century, a paraplegic Marine is di...","Ingenious_Film_Partners,Twentieth_Century_Fox_...","Sam_Worthington,Zoe_Saldana,Sigourney_Weaver,S...","Stephen_E._Rivkin,Rick_Carter,Christopher_Boye..."
1,285,"Adventure,Fantasy,Action","ocean,drug_abuse,exotic_island,east_india_trad...",Pirates of the Caribbean: At World's End,"At the end of the world, the adventure begins.","Captain Barbossa, long believed to be dead, ha...","Walt_Disney_Pictures,Jerry_Bruckheimer_Films,S...","Johnny_Depp,Orlando_Bloom,Keira_Knightley,Stel...","Dariusz_Wolski,Gore_Verbinski,Jerry_Bruckheime..."
2,206647,"Action,Adventure,Crime","spy,based_on_novel,secret_agent,sequel,mi6,bri...",Spectre,A Plan No One Escapes,A cryptic message from Bond’s past sends him o...,"Columbia_Pictures,Danjaq,B24","Daniel_Craig,Christoph_Waltz,Léa_Seydoux,Ralph...","Thomas_Newman,Sam_Mendes,Anna_Pinnock,John_Log..."
3,49026,"Action,Crime,Drama,Thriller","dc_comics,crime_fighter,terrorist,secret_ident...",The Dark Knight Rises,The Legend Ends,Following the death of District Attorney Harve...,"Legendary_Pictures,Warner_Bros.,DC_Entertainme...","Christian_Bale,Michael_Caine,Gary_Oldman,Anne_...","Hans_Zimmer,Charles_Roven,Christopher_Nolan,Ch..."
4,49529,"Action,Adventure,Science_Fiction","based_on_novel,mars,medallion,space_travel,pri...",John Carter,"Lost in our world, found in another.","John Carter is a war-weary, former military ca...",Walt_Disney_Pictures,"Taylor_Kitsch,Lynn_Collins,Samantha_Morton,Wil...","Andrew_Stanton,Andrew_Stanton,John_Lasseter,Co..."
...,...,...,...,...,...,...,...,...,...
4798,9367,"Action,Crime,Thriller","united_states–mexico_barrier,legs,arms,paper_k...",El Mariachi,"He didn't come looking for trouble, but troubl...",El Mariachi just wants to play his guitar and ...,Columbia_Pictures,"Carlos_Gallardo,Jaime_de_Hoyos,Peter_Marquardt...","Robert_Rodriguez,Robert_Rodriguez,Robert_Rodri..."
4799,72766,"Comedy,Romance",,Newlyweds,A newlywed couple's honeymoon is upended by th...,A newlywed couple's honeymoon is upended by th...,,"Edward_Burns,Kerry_Bishé,Marsha_Dietlein,Caitl...","Edward_Burns,Edward_Burns,Edward_Burns,William..."
4800,231617,"Comedy,Drama,Romance,TV_Movie","date,love_at_first_sight,narration,investigati...","Signed, Sealed, Delivered",NaN,"""Signed, Sealed, Delivered"" introduces a dedic...","Front_Street_Pictures,Muse_Entertainment_Enter...","Eric_Mabius,Kristin_Booth,Crystal_Lowe,Geoff_G...","Carla_Hetland,Harvey_Kahn,Adam_Sliwinski,Marth..."
4801,126186,,,Shanghai Calling,A New Yorker in Shanghai,When ambitious New York attorney Sam is sent t...,,"Daniel_Henney,Eliza_Coupe,Bill_Paxton,Alan_Ruc...","Daniel_Hsia,Daniel_Hsia"
4802,25975,Documentary,"obsession,camcorder,crush,dream_girl",My Date with Drew,NaN,Ever since the second grade when he first saw ...,"rusty_bear_entertainment,lucky_crow_films","Drew_Barrymore,Brian_Herzlinger,Corey_Feldman,...","Clark_Peterson,Andrew_Reimer,Brian_Herzlinger,..."

In [16]:
table.fillna('',inplace = True)

,id,genres,keywords,title,tagline,overview,production_companies,cast,crew
0,19995,"Action,Adventure,Fantasy,Science_Fiction","culture_clash,future,space_war,space_colony,so...",Avatar,Enter the World of Pandora.,"In the 22nd century, a paraplegic Marine is di...","Ingenious_Film_Partners,Twentieth_Century_Fox_...","Sam_Worthington,Zoe_Saldana,Sigourney_Weaver,S...","Stephen_E._Rivkin,Rick_Carter,Christopher_Boye..."
1,285,"Adventure,Fantasy,Action","ocean,drug_abuse,exotic_island,east_india_trad...",Pirates of the Caribbean: At World's End,"At the end of the world, the adventure begins.","Captain Barbossa, long believed to be dead, ha...","Walt_Disney_Pictures,Jerry_Bruckheimer_Films,S...","Johnny_Depp,Orlando_Bloom,Keira_Knightley,Stel...","Dariusz_Wolski,Gore_Verbinski,Jerry_Bruckheime..."
2,206647,"Action,Adventure,Crime","spy,based_on_novel,secret_agent,sequel,mi6,bri...",Spectre,A Plan No One Escapes,A cryptic message from Bond’s past sends him o...,"Columbia_Pictures,Danjaq,B24","Daniel_Craig,Christoph_Waltz,Léa_Seydoux,Ralph...","Thomas_Newman,Sam_Mendes,Anna_Pinnock,John_Log..."
3,49026,"Action,Crime,Drama,Thriller","dc_comics,crime_fighter,terrorist,secret_ident...",The Dark Knight Rises,The Legend Ends,Following the death of District Attorney Harve...,"Legendary_Pictures,Warner_Bros.,DC_Entertainme...","Christian_Bale,Michael_Caine,Gary_Oldman,Anne_...","Hans_Zimmer,Charles_Roven,Christopher_Nolan,Ch..."
4,49529,"Action,Adventure,Science_Fiction","based_on_novel,mars,medallion,space_travel,pri...",John Carter,"Lost in our world, found in another.","John Carter is a war-weary, former military ca...",Walt_Disney_Pictures,"Taylor_Kitsch,Lynn_Collins,Samantha_Morton,Wil...","Andrew_Stanton,Andrew_Stanton,John_Lasseter,Co..."
...,...,...,...,...,...,...,...,...,...
4798,9367,"Action,Crime,Thriller","united_states–mexico_barrier,legs,arms,paper_k...",El Mariachi,"He didn't come looking for trouble, but troubl...",El Mariachi just wants to play his guitar and ...,Columbia_Pictures,"Carlos_Gallardo,Jaime_de_Hoyos,Peter_Marquardt...","Robert_Rodriguez,Robert_Rodriguez,Robert_Rodri..."
4799,72766,"Comedy,Romance",,Newlyweds,A newlywed couple's honeymoon is upended by th...,A newlywed couple's honeymoon is upended by th...,,"Edward_Burns,Kerry_Bishé,Marsha_Dietlein,Caitl...","Edward_Burns,Edward_Burns,Edward_Burns,William..."
4800,231617,"Comedy,Drama,Romance,TV_Movie","date,love_at_first_sight,narration,investigati...","Signed, Sealed, Delivered",,"""Signed, Sealed, Delivered"" introduces a dedic...","Front_Street_Pictures,Muse_Entertainment_Enter...","Eric_Mabius,Kristin_Booth,Crystal_Lowe,Geoff_G...","Carla_Hetland,Harvey_Kahn,Adam_Sliwinski,Marth..."
4801,126186,,,Shanghai Calling,A New Yorker in Shanghai,When ambitious New York attorney Sam is sent t...,,"Daniel_Henney,Eliza_Coupe,Bill_Paxton,Alan_Ruc...","Daniel_Hsia,Daniel_Hsia"
4802,25975,Documentary,"obsession,camcorder,crush,dream_girl",My Date with Drew,,Ever since the second grade when he first saw ...,"rusty_bear_entertainment,lucky_crow_films","Drew_Barrymore,Brian_Herzlinger,Corey_Feldman,...","Clark_Peterson,Andrew_Reimer,Brian_Herzlinger,..."

In [17]:
table['tags'] = table['genres']+','+table['keywords']+','+table['tagline']+','+table['overview']+','+table['production_companies']+','+table['cast']+','+table['crew']

In [18]:
table = table[['id','title','tags']]

In [19]:
table['title'] = table['title'].str.lower()
table['tags'] = table['tags'].str.lower()

In [20]:
table

,id,title,tags
0,19995,avatar,"action,adventure,fantasy,science_fiction,cultu..."
1,285,pirates of the caribbean: at world's end,"adventure,fantasy,action,ocean,drug_abuse,exot..."
2,206647,spectre,"action,adventure,crime,spy,based_on_novel,secr..."
3,49026,the dark knight rises,"action,crime,drama,thriller,dc_comics,crime_fi..."
4,49529,john carter,"action,adventure,science_fiction,based_on_nove..."
...,...,...,...
4798,9367,el mariachi,"action,crime,thriller,united_states–mexico_bar..."
4799,72766,newlyweds,"comedy,romance,,a newlywed couple's honeymoon ..."
4800,231617,"signed, sealed, delivered","comedy,drama,romance,tv_movie,date,love_at_fir..."
4801,126186,shanghai calling,",,a new yorker in shanghai,when ambitious new ..."
4802,25975,my date with drew,"documentary,obsession,camcorder,crush,dream_gi..."

In [21]:
table['tags'] = table['tags'].str.replace('.','')

In [22]:
table.loc[0,'tags']

"action,adventure,fantasy,science_fiction,culture_clash,future,space_war,space_colony,society,space_travel,futuristic,romance,space,alien,tribe,alien_planet,cgi,marine,soldier,battle,love_affair,anti_war,power_relations,mind_and_soul,3d,enter the world of pandora,in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization,ingenious_film_partners,twentieth_century_fox_film_corporation,dune_entertainment,lightstorm_entertainment,sam_worthington,zoe_saldana,sigourney_weaver,stephen_lang,michelle_rodriguez,giovanni_ribisi,joel_david_moore,cch_pounder,wes_studi,laz_alonso,dileep_rao,matt_gerald,sean_anthony_moran,jason_whyte,scott_lawrence,kelly_kilgour,james_patrick_pitt,sean_patrick_murphy,peter_dillon,kevin_dorman,kelson_henderson,david_van_horn,jacob_tomuri,michael_blain-rozgay,jon_curry,luke_hawker,woody_schultz,peter_mensah,sonia_yee,jahnel_curfman,ilram_choi,kyla_warren,lisa_roumain,debra_wilson,chris_mala,taylor_kibby,jodie_landau,julie_lamm,cullen_b_madden,joseph_brady_madden,frankie_torres,austin_wilson,sara_wilson,tamica_washington-miller,lucy_briant,nathan_meister,gerry_blair,matthew_chamberlain,paul_yates,wray_wilson,james_gaylyn,melvin_leno_clark_iii,carvon_futrell,brandon_jelkes,micah_moch,hanniyah_muhammad,christopher_nolen,christa_oliver,april_marie_thomas,bravita_a_threatt,colin_bleasdale,mike_bodnar,matt_clayton,nicole_dionne,jamie_harrison,allan_henry,anthony_ingruber,ashley_jeffery,dean_knowsley,joseph_mika-hunt,terry_notary,kai_pantano,logan_pithyou,stuart_pollock,raja,gareth_ruck,rhian_sheehan,t_j_storm,jodie_taylor,alicia_vela-bailey,richard_whiteside,nikie_zambo,julene_renee,stephen_e_rivkin,rick_carter,christopher_boyes,christopher_boyes,mali_finn,james_horner,james_cameron,james_cameron,james_cameron,james_cameron,james_cameron,andrew_menzies,jill_brooks,margery_simkin,kevin_ishioka,dick_bernstein,shannon_mills,dennie_thorpe,jana_vance,deborah_lynn_scott,jon_landau,sean_haworth,kim_sinclair,kim_sinclair,richard_f_mays,laeta_kalogridis,mayes_c_rubeo,mauro_fiore,scott_herbertson,woody_schultz,linda_devetta,linda_devetta,richard_bluck,simon_bright,richard_martin,steve_r_moore,john_refoua,karl_j_martin,chiling_lin,ilram_choi,steven_quale,carla_meyer,nick_bassett,jill_cormack,andy_mclaren,terry_notary,garrett_warren,jonathan_rothbart,stefan_dechant,todd_cherniawsky,miranda_rivers,robert_stromberg,john_harding,roberto_de_angelis,mike_smithson,alain_lalanne,lucas_salton,janace_tashjian,stephen_rosenbaum,frankie_karena,lisa_lovaas,jonathan_fawkner,robert_bavin,anthony_almaraz,carolyn_m_fenton,beth_koenigsberg,sam_page,tex_kadonaga,kim_foscato,tammy_s_lee,denny_caira,james_waitkus,addison_teague,c_scott_baker,luke_caska,david_chow,jonathan_dyer,joseph_hiura,rebecca_jellie,robert_andrew_johnson,mike_stassi,john_villarino,jeffrey_wisniewski,cheryl_nardi,marshall_winn,gwendolyn_yates_whittle,william_stein,lula_washington,chris_del_conte,r_christopher_white,dan_lemmon,tim_nielsen,michael_mulholland,thomas_nittmann,edson_williams,christine_carr,john_bruno,david_emmerichs,christopher_scarabosio,jennifer_teves,brigitte_yorke,ken_fischer,iain_hutton,steve_ingram,joyce_cox,jenny_foster,christopher_marino,jim_milton,cyndi_ochs,lucas_putnam,anthony_'max'_ivins,john_knoll,eric_saindon,wayne_stables,david_stinnett,guy_williams,stuart_thorp,giles_coburn,mark_fellman,scott_sprague,jeremy_hollobon,orlando_meunier,taisuke_tanimura,lilia_mishel_acevedo,alejandro_m_hernandez,marvin_hall,judy_alley,mike_perry,andrew_morley,seth_engstrom,eric_oliver,matsune_suzuki,paul_tobin,roxane_griffin,arun_ram-mohan,georgia_lockhart-adams,thrain_shadbolt,brad_alexander,shadi_almassizadeh,simon_clutterbuck,graeme_demmocks,adrian_fernandes,mitch_gates,jerry_kung,andy_lomas,sebastian_marino,matthias_menz,sergei_nevshupov,philippe_rebours,michael_takarangi,david_weitzberg,ben_white,min_windle"

In [23]:
table = table.drop(table.sample(n=3000, random_state=42).index)

In [24]:
table.to_csv('cleaned_data.csv', index = False)